### ISSUE TITLE
Support enable .env in project

### ISSUE THREAD

**Issue by ZihaoPri** [Ashald/EnvFile#120]
I have multiple pytests in my project. Every time I run a new test, I need to set up the Envfile inside Run/Debug configuration.
It would be nice if there were a way to make it used the same .env file for every test in the project.

**Comment by vojkny** [comment]
This doesn't concern only tests, but also all the microservices. Each of them require manual setup currently.

**Comment by ZihaoPri** [comment]
Hi @knyttl, 
In fact, I found that we could setting environment variables for multiple running objects by using an IDE template configuration.
To do this you can open IDE's `Run/Debug Configuration` to select the type you need and set Envfile for it.
![image](https://user-images.githubusercontent.com/37468677/100187734-af84aa00-2f23-11eb-8a3b-d4d5aef52d97.png)

**Comment by vojkny** [comment]
> Hi @knyttl,
> In fact, I found that we could setting environment variables for multiple running objects by using an IDE template configuration.

very helpful indeed!
