### ISSUE TITLE
Feature request: different text color for comments

### ISSUE THREAD

**Issue by barakbbn** [Ashald/EnvFile#141]
It would be better if comments would have different color than the rest of the entries (i.e. grayed)

```py
MODE="test"
# PREFIX="your_prefix_here_"
MAX_TASKS=10
JOB={"queue":"${PREFIX}jobber"}
```

So when someone put a value for **PREFIX** he/she won't forget to uncomment it (like it keeps happening for several people already)

**Comment by ashald** [comment]
This plugin does not provide syntax support for `.env` files.
I heard https://plugins.jetbrains.com/plugin/11594-properties does something like that though.

Alternatively, I'd be curious to see a PR that would add that.
