### ISSUE TITLE
Plugin Installation Error

### ISSUE THREAD

**Issue by cn-core** [Ashald/EnvFile#143]
![image](https://user-images.githubusercontent.com/30290251/127279460-a014c430-35f4-49c7-b88a-05a81524a079.png)

**Comment by agaengel** [comment]
This is a duplicate with https://github.com/ashald/EnvFile/issues/140

**Comment by cn-core** [comment]
thank you ...

**Comment by ashald** [comment]
Closing as a duplicate, fixed now.
