### ISSUE TITLE
Plugin not installing after update

### ISSUE THREAD

**Issue by meneses-pt** [Ashald/EnvFile#145]
I just updated PyCharm to 2021.2, and this plugin seems to have been uninstalled and I can't install it again even after restarting PyCharm.

When trying to install the plugin I get the following message: "Plugin 'EnvFile' was not installed: Failed to load the plugin descriptor from the downloaded archive. The archive is probably not an IntelliJ plugin.".

**Comment by djtsov** [comment]
@meneses-pt Duplicated https://github.com/ashald/EnvFile/issues/140
Install this version:
https://github.com/ashald/EnvFile/issues/140#issuecomment-883210881
