### ISSUE TITLE
PYTHONPATH cannot bet set

### ISSUE THREAD

**Issue by franzlst** [Ashald/EnvFile#15]
The `PYTHONPATH` specified in the .env file seems to be overridden by PyCharm. Even with a very simple .env file like

```
PYTHONPATH=xyz
```

and unchecking "Add content/source roots to PYTHONPATH", the `PYTHONPATH` ends up being taken from the bash in which PyCharm was started.
Any other key, like

```
PATH=xyz
```

is working.

I was verifying this by printing `os.environ`.

**Comment by ashald** [comment]
I'm not sure that it's doable with PyCharm (as it's doing a lot of magic related to Python environment) but I'll check whether I can find a way to do that.

**Comment by ashald** [comment]
It's impossible to implement due to the way how PyCharm handles `PYTHONPATH` so closing this as won't fix.
