### ISSUE TITLE
Fails to install on on Ultimate edition of IDEA 2021.2 from July 27, 2021 build

### ISSUE THREAD

**Issue by IgorNetOp** [Ashald/EnvFile#153]
![image](https://user-images.githubusercontent.com/49119182/129895883-2c2015f6-142e-4764-a349-4239fd379901.png)

**Comment by msvidal2** [comment]
.

**Comment by ghost** [comment]
[146](https://github.com/ashald/EnvFile/issues/146)

**Comment by ineph** [comment]
#151
Easy solution that work for me (note that is not an ideal solution as he says):
 _Originally posted by @Doug-Cleo in https://github.com/ashald/EnvFile/issues/151#issuecomment-898447980_

**Comment by ashald** [comment]
Closing as duplicate of #151
