### ISSUE TITLE
No tab showing up after installing on IntelliJ 2021.2.1

### ISSUE THREAD

**Issue by akirilyuk** [Ashald/EnvFile#156]
After installing the plugin, I am not able to see the EnvFile tab.

![image](https://user-images.githubusercontent.com/45361199/133471440-810fbe84-94ce-4358-8cde-15bcc9420646.png)

![image](https://user-images.githubusercontent.com/45361199/133471539-2b6048bc-3854-42ef-8cf3-80b8c051f4ad.png)

**Comment by piavgh** [comment]
Same with Goland 2021.3.2

**Comment by ashald** [comment]
Should be fixed in 3.4.1
