### ISSUE TITLE
No options in menu for adding file in GoLand

### ISSUE THREAD

**Issue by martin-sucha** [Ashald/EnvFile#157]
GoLand 2021.2.3
Build #GO-212.5284.40, built on September 14, 2021

EnvFile 3.2.2

![Screenshot from 2021-09-21 15-40-47-crop](https://user-images.githubusercontent.com/2007393/134185004-9b921f96-9323-4e6f-abc4-83bb187a95db.png)

**Comment by paulb39** [comment]
I had the same issue.
To fix you need to add a .env file in the project folder. So I added a vars.env file, reloaded intelij, and then in that menu the file came up.
This information should be added to the main project page - or there should be a "add new file" option in the drop down.

**Comment by ashald** [comment]
That's weird, I couldn't reproduce this.
