### ISSUE TITLE
Add possibility to append to an existing variable

### ISSUE THREAD

**Issue by franzlst** [Ashald/EnvFile#16]
For an .env script like

```
PATH=/my/path:${PATH}
```

the plugin should prepend the current `PATH` with `/my/path`. Thus, if `PATH=/another/path`, the environment should result in `PATH=/my/path:/another/path`. Currently, `PATH` ends up being `/my/path:${PATH}`

**Comment by ashald** [comment]
Proper support would required shell script interpreter invocation but maybe we can go with simplified support where only `$NAME` or `${NAME}` is supported (as opposed to `${NAME:-default}` and so on). Would it suit your use-case?

**Comment by franzlst** [comment]
Yes, that would be perfect. That would be the same behavior as in the "Environmental variables" that you can set manually in the PyCharm run configuration.

**Comment by ashald** [comment]
I'm going to add this as an optional feature using https://commons.apache.org/proper/commons-lang/javadocs/api-3.3.2/org/apache/commons/lang3/text/StrSubstitutor.html

**Comment by ashald** [comment]
Implemented, will be released soon.
