### ISSUE TITLE
EnvFile plugin not supported in IDEA 2021.2

### ISSUE THREAD

**Issue by BorzdeG** [Ashald/EnvFile#162]

**Comment by Josef-Reichardt** [comment]
It does also not work in 2021.3:
![Plugin error: File '~/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.5744.223.plugins/EnvFile/lib/envfile-3.2.1.jar' contains invalid plugin descriptor](https://user-images.githubusercontent.com/1203740/146882074-89420ccd-865d-4dc1-b50d-6e23114cb2f9.png)

**Comment by ashald** [comment]
Did you try version `3.2.2`?

**Comment by Josef-Reichardt** [comment]
No, now I found out that I haven't installed this plugin. I don't know why this message appears, maybe another plugin brings this as dependency or there are any old files in a cache directory of IntelliJ IDEA? Now I have installed the plugin (version `3.2.2`) using the plugin marketplace and the error is gone. :+1:

**Comment by mklueh** [comment]
Same, have this issue since ages withouth explicitly having installed the plugin
