### ISSUE TITLE
System env var expansion not working

### ISSUE THREAD

**Issue by damiansima** [Ashald/EnvFile#169]
When loading an env var that looks like: 

`MY_VAR=${AN_ACTUAL_ENV_VAR}`

Where the variable AN_ACTUAL_ENV_VAR is part of the system (in my particular case set through .bash_profile) the content of MY_VAR evaluates "" (empty string). 

The run dialog in Idea shows the env var (AN_ACTUAL_ENV_VAR) being loaded with the actual content. At first I though it was idea not picking it up, but no. 

Is this a know issue (I failed to find a report of it)?
Is there a work around?

**Comment by ben-peterson-at-numerated** [comment]
I'm having the same issue with EnvFile.  As a workaround, PyCharm offers a nice copy/paste feature in its native Environment Variables dialog - I copied and pasted the variable values I needed from the "System" list to the "User" list.  Somewhat inconvenient, but better than typing by hand.

**Comment by ashald** [comment]
Should be fixed in 3.4.1
