### ISSUE TITLE
Allow wrapping the value in " marks to escape spaces, etc

### ISSUE THREAD

**Issue by cancan101** [Ashald/EnvFile#17]
eg `FOO="ALEX R\nwas here"`
Right now, the " are left in the final string.

**Comment by ashald** [comment]
Sonds legit. BTW, did you try `yaml` format? Or it's important to you to use `.env`?

**Comment by cancan101** [comment]
I want to use `.env` so I can also `source` the file in unit tests.

**Comment by uhavin** [comment]
I am facing the exact same problem. Would much appreciate a fix.

**Comment by ashald** [comment]
I'll try to include it into the next release which I hope will happen before the end of the year.

**Comment by ashald** [comment]
Fixed in `v2.0` that's coming anytime soon.
