### ISSUE TITLE
How can I remember files, so I won't need to reapply it after restart?How to apply the file to the whole project?

### ISSUE THREAD

**Issue by berserk-fan** [Ashald/EnvFile#170]

**Comment by ashald** [comment]
Have you tried setting it up in the template?

**Comment by ryanfox1985** [comment]
I have the same issue with Scala, even using the Test template, Idea doesn't load the envfile when a new testsuite is created. Also as @mamat14 mentioned every time I restart Idea, the envfile tab resets to default values (all blank and envfile unselected) and I need to load again.

EnvFile version: 3.2.2
IntelliJ IDEA 2021.3.1 (also with the CE edition happens)
MacOS Monterey (12.1)

**Comment by ashald** [comment]
Apparently it's something specific to ScalaTest run configuration.
Please create a dedicated issue.
