### ISSUE TITLE
Separate EnvFile Configuration between Run Configurations

### ISSUE THREAD

**Issue by ansidev** [Ashald/EnvFile#175]
Expected:
- Run Configuration (RC) A: Load app.env.dev
- Run Configuration B: Load app.env.test

Problem: The EnvFile configuration is a global config, so if I load `app.env.dev` in RC A, RC B will load `app.env.dev` the next time unless I update EnvFile config.

**Comment by ashald** [comment]
EnvFile is configured per run configuration.

**Comment by ansidev** [comment]
@ashald

> EnvFile is configured per run configuration.

We expected this, but it doesn't work as expected. That's why I created this issue. However, I guess you didn't get it.

**Comment by ashald** [comment]
You did not mentioned the IDE so IDK how to reproduce it, but I just checked PyCharm and each run configuration had its own changes saved independently.

If you're still seeing the issue, you might want to try re-creating your project file.

**Comment by ansidev** [comment]
@ashald

Although this issue is from your plugin and I didn't use PyCharm, however, you said you tested this issue on PyCharm. So I made a record to reproduce this issue on PyCharm.

Steps to reproduce

1. Install PyCharm.
2. Install the plugin EnvFile and restart PyCharm.
3. Create a simple Python program containing 3 files:

main.py:

```python
import os


def print_env():
    print(os.environ['PY_ENV'])


if __name__ == '__main__':
    print_env()
```

app.env.dev:

```
PY_ENV=dev
```

app.env.test:

```
PY_ENV=test
```

4. Create 2 run configurations as recorded in this video `[dev] main` and `[test] main`.

https://user-images.githubusercontent.com/6688235/203485140-1ce8dfb7-de62-4fa5-8207-a60b24b8d155.mov

As you can see in the above video:

| Note            | [dev] main           | [test] main          |
| --------------- | -------------------- | -------------------- |
| Before updating | app.env.dev (00:05)  | app.env.dev (00:06)  |
| After updating  | app.env.test (00:20) | app.env.test (00:16) |

This means that the env file path is always the same for all run configurations.

**Test Environment Information** (if necessary)

- macOS 12.6.1.
- PyCharm 2022.2.3 (Professional Edition).
- Python 3.10.8 (Pipenv) (as recorded in the video).
- EnvFile 3.4.1.

Finally, I don't know how you reproduced this issue, but I doubt that after recording this video.
