### ISSUE TITLE
.env file picker on Mac not showing ".env file" (i.e., file with extension only)

### ISSUE THREAD

**Issue by matthewcornell** [Ashald/EnvFile#177]
Hi There. Thanks a ton for your tool. I've been putting off updating IDEA because of past issues with EnvFile, but I finally got around to trying the two together. First thing I noticed is that the file picker doesn't show my file named ".env" in my project, i.e., files with an extension but no name. It does allow picking files with both name and extension. It's my understanding that ".env" is a common name. Thank you.

versions:
- EnvFile 3.2.2
- IntelliJ IDEA 2021.3.3 (Ultimate Edition)
- macOS Catalina (10.25.7)

![file-chooser](https://user-images.githubusercontent.com/1034007/162324679-f756cd39-7bd9-4b86-8e0f-1247437070c3.png)

**Comment by ashald** [comment]
Have yo tried instructions from readme? https://github.com/ashald/EnvFile#hidden-files

**Comment by matthewcornell** [comment]
Damn, sorry about that. I forgot to RTFM. I assumed that the Finder setting that I changed ages ago in the Terminal would carry through to the select dialogs. Thanks again for the excellent tool.

![Screen Shot 2022-04-08 at 9 48 08 AM](https://user-images.githubusercontent.com/1034007/162450747-4e5339c8-d4aa-4106-9dc3-51beb3eda1e4.png)
