### ISSUE TITLE
Stop working after changing branch

### ISSUE THREAD

**Issue by PATAPOsha** [Ashald/EnvFile#187]
After changing branch plugin stops working. Environment variables become empty. However, .env file still marked as active in "Run/debug configuration" section. Tried to disable/enable it manually and delete/add .env file in configuration window - nothing helps.

Tried on PyCharm 2022.1.1, MacOS 12.4

**Comment by hammersharkfish** [comment]
Have you found a solution . I have the same issue .

**Comment by ashald** [comment]
That's not enough details to investigate a potential issue (even if there is one).
Feel free to reopen with more details.
