### ISSUE TITLE
It installs but doesn't work in Pycharm 2022.2

### ISSUE THREAD

**Issue by pvicente** [Ashald/EnvFile#188]
Plugin installs but doesn't work on Pycharm version `Build #PY-222.3345.131, built on July 27, 2022`

**Comment by OlehChyhyryn** [comment]
Duplicate of https://github.com/ashald/EnvFile/issues/185

**Comment by vetruvet** [comment]
Seeing the same thing on IntelliJ IDEA version `Build #IU-222.3345.118, built on July 26, 2022`

**Comment by fabiopedrosa** [comment]
Same here 😢

**Comment by unluckynelson** [comment]
The workaround for now is:

- Copy your env file contents to clipboard
- Edit your run configuration's environment variables
- Click the small paste button

**Comment by pythrick** [comment]
Same here :(

**Comment by 1oglop1** [comment]
I just updated to RC 2022.2.2 `Build #PY-222.4167.4, built on August 31, 2022` and the plugin works there, so no need to downgrade, just opt in EAP 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/7480694/188848803-ee0e6f45-5b79-47e6-a729-d0eae098e7fc.png">

**Comment by zack-kimble** [comment]
For me upgrading to RC 2022.2.2 does not work on Ubuntu.

That is pycharm-professional RC 2022.2.2 (Build #PY-222.4167.4, built on August 31, 2022) via snap pycharm-professional latest/candidate channel  on Ubuntu 20.04

Downgrading to 2022.2.1 fixes the problem.

**Comment by ashald** [comment]
Follow #185 for updates.
