### ISSUE TITLE
Support of Django manage.py console

### ISSUE THREAD

**Issue by pymen** [Ashald/EnvFile#19]
Please allow to use EnvFile in
https://www.jetbrains.com/help/pycharm/2016.1/running-tasks-of-manage-py-utility.html
picture: http://joxi.ru/RmzQLZ4tzd4jrO

**Comment by ashald** [comment]
This is not feasible to implement considering current design of the plugin so it won't be included in `v2.0` but may be added in future. Stay tuned.

**Comment by ashald** [comment]
Closing in favor of #7.
