### ISSUE TITLE
Semicolons replaced with colons

### ISSUE THREAD

**Issue by jroush-vf** [Ashald/EnvFile#191]
EnvFile is replacing semicolons in variable values with colons.  This behavior is not documented (AFAIK) and there doesn't seem to be any way to disable or escape it.  

I am running PyCharm on Windows 11, but the project and .env file are in the WSL2 filesystem.

PyCharm Info:

    PyCharm 2022.1.3 (Professional Edition)
    Build #PY-221.5921.27, built on June 21, 2022
    Runtime version: 11.0.15+10-b2043.56 amd64
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
    Windows 11 10.0
    GC: G1 Young Generation, G1 Old Generation
    Memory: 2016M
    Cores: 16
    Non-Bundled Plugins:
        ru.meanmail.plugin.requirements (2022.3-2022.1)
        net.ashald.envfile (3.2.2)

**Comment by ashald** [comment]
I couldn't reproduce this on macOS on PyCharm 2022.2.4 with EnvFile v3.4.1

**Comment by scriptator** [comment]
I can confirm that this happens as well in IntelliJ IDEA 2023.3.2 (Ultimate Edition) and the latest EnvFile version, but only on Windows 10.
