### ISSUE TITLE
Why the command line used to extract information for the export isn't executed?

### ISSUE THREAD

**Issue by acarlstein** [Ashald/EnvFile#192]
# Summary 

_First, thank you for taking a look into the current issue I created. Much appreciated._

I need some environment variables, which are required for the Spring Boot app to run, which values are obtained from the Secret Manager in GCP.

# Description

Normally, if I do the following, it works:

1) I create a file with the exports (i.e.: .envs):

```bash
export EVENTHUB_ACCESS_KEY=$(gcloud secrets versions access 1 --secret eventhub-eastus-account-key)
```

2) I run the command `source .envs' 

3) I run the command `env` and I can see that the `gcloud` command was executed.

`EVENTHUB_ACCESS_KEY=access+key+would+extracted+and+shown+here=`

However, this isn't the case with IntelliJ and EnvFile.

In IntelliJ, If I add the export here:

![image](https://user-images.githubusercontent.com/5709926/193301143-e6262ed8-f84a-4105-8916-dbc064a2162b.png)

![image](https://user-images.githubusercontent.com/5709926/193301382-05a1d0da-f503-4aab-8acd-a8bf40572d3d.png)

Then, the `gcloud` command isn't executed.

In EnvFile, If I add the following to the `.env` file, per the instructions, and set this as:

![image](https://user-images.githubusercontent.com/5709926/193302038-52b2e168-fabb-4010-991f-ed2aeeb946d6.png)

or

![image](https://user-images.githubusercontent.com/5709926/193302117-2911db14-64e9-4ccd-a148-a8dd16ace086.png)

Then, it does the same thing.

# Acceptance Criteria

I would like to be able to add the line below, into the `.env` file, and have the `gcloud` command executed:
```bash
EVENTHUB_ACCESS_KEY=$(gcloud secrets versions access 1 --secret eventhub-eastus-account-key)
```

So, when I run the Spring Boot in IntelliJ, I can see the environment variable (or see the values via adding a breakpoint) with this code example:
```kotlin
fun main(args: Array<String>) {
    val log = LoggerFactory.getLogger(GCloudEnvironmentTestApplication::class.java)
    log.debug("ENVS")
    val env = System.getenv()
    env.forEach { (k, v) -> log.debug("$k:$v") }
    runApplication<GCloudEnvironmentTestApplication>(*args)
}
```

**Comment by ashald** [comment]
If you look carefully, you'd notice that UI shows curly braces and you use round braces. :) That is to say that EnvFile emulates bash-like interpolation, but does not actually execute commands within `$(...)`.
That being said, as of last release when you specify a file, you can mark it as executable and this way EnvFile will run it and interpret stdout as .env or JSON/YAML depending on your settings.
You can create a file that would execute `gcloud` and output the env vars, and run that file with EnvFile to get them into your run configuration.
