### ISSUE TITLE
EnvFile not applied when reading `application.properties`

### ISSUE THREAD

**Issue by CodingAleCR** [Ashald/EnvFile#204]
I have a Spring Boot application running with configurations set in `application.properties` pointing to env vars in a `.env` file. However, when running the project, it does not recognize the environment variables. This used to work a while back (a couple of years ago) but now it does not.

Here's an example of how it's setup:

`.env`

```txt
SOME_ENV_VAR=mysecretvalue
```

`application.properties`

```txt
some.config.envvar=${SOME_ENV_VAR}
```

If I substitute all values in the `application.properties` for the ones in `.env` then the project runs just fine.

**IDE: IntelliJ CE**
**Configuration Type: Gradle task or Application**
**EnvFile settings:**
<img width="709" alt="Screen Shot 2022-11-30 at 18 18 20" src="https://user-images.githubusercontent.com/12262852/204935761-49f0b871-c517-46ed-809d-3d0d15e1a75e.png">

**Comment by nevotz** [comment]
happens also to me , intellij 2021.3

**Comment by CodingAleCR** [comment]
@nevotz in my case it was solved by upgrading Gradle on my project. 

I understand this is not the best solution or something that everyone can do on their projects but I hope it helps. 🙏🏼
