### ISSUE TITLE
When running tests in IntelliJ the `envfile` if not loaded

### ISSUE THREAD

**Issue by PhoenixRe32** [Ashald/EnvFile#210]
```
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Licensed to XXX
Subscription is active until XXX.
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

```

It's a Kotlin project if it matters. 

![image](https://user-images.githubusercontent.com/35810509/214821432-58946b20-3bce-4da5-8153-8ab4f9100e9c.png)

![image](https://user-images.githubusercontent.com/35810509/214821585-6c65dd44-9334-4a9d-a766-ce0a6e03d052.png)
I tried it also by not using substitution and just using the home folder path

**Comment by zzerjae** [comment]
I think your dev.env should be remove `export `

```
As-Is
export TESTCONTAINERS_DOCKER...
export DOCKER_HOST...

To-Be

TESTCONTAINERS_DOCKER...
DOCKER_HOST...
```

**Comment by PhoenixRe32** [comment]
🤦 Copy Paste silliness
