### ISSUE TITLE
Security vulnerability in apache commons-text v1.9

### ISSUE THREAD

**Issue by ryanwilliamquinn** [Ashald/EnvFile#226]
Latest version is 1.11

See here https://mvnrepository.com/artifact/org.apache.commons/commons-text

**Comment by ryanwilliamquinn** [comment]
looks like it is already updated to 1.10, maybe it just needs to cut a new release? Looks like most recent release (3.4.1) is still using v1.9, though the develop branch has 1.10.

**Comment by ashald** [comment]
Uploaded v3.4.2 wit the fix.
