### ISSUE TITLE
Remember last n files

### ISSUE THREAD

**Issue by grundic** [Ashald/EnvFile#23]
Great plugin, enjoying using it so much!

One of the issues I come over is necessity so select same file multiple times when running different scripts. Is it possible to save recent used files and add them to the drop down menu (next to `.env file` and `JSON/YAML file`)?

Thank you.

**Comment by ashald** [comment]
The more I think about it the this feature makes sense.

I'm wondering whether we should keep history in the project file or just store it in memory so it'll reset after IDE re-start.

**Comment by grundic** [comment]
I would prefer to keep the history in a file, as this would be more convenient. For example, I store some credentials in those files and using them among different projects. Also I do a lot of branch switching and running arbitrary scripts. This would make selecting correct env file much easier.

**Comment by ashald** [comment]
Implemented in version `2.1.0` which was released and pending review from JetBrains.

**Comment by grundic** [comment]
Awesome! Can't wait to update and start using it. Thank you!

**Comment by ashald** [comment]
Let me know whether you will have any feedback on how it works. ;)
