### ISSUE TITLE
EnvFile configuration resets on restart for ScalaTest setups

### ISSUE THREAD

**Issue by Thejipppp** [Ashald/EnvFile#236]
Example setup:
![image](https://github.com/user-attachments/assets/6906baca-0c5f-48d4-93c2-8822626035ce)
After restart:
![image](https://github.com/user-attachments/assets/34635fd4-e2ef-4697-b725-b286ca04686a)

**Comment by nedmules-sked** [comment]
This has been a problem for quite a long time but it used to work. See also https://github.com/ashald/EnvFile/issues/170

There is also a problem with ScalaTest run configuration templates - if I set up an EnvFile configuration in the template, then create a new ScalaTest run configuration, the EnvFile config doesn't get applied.
Like the original reported problem, the ScalaTest configuration is lost after IntelliJ is restarted.

**Comment by Thejipppp** [comment]
As of IntelliJ IDEA 2024.3.1, there is native support for env files, omitting the need for using this plugin.
