### ISSUE TITLE
run configuration not finding env vars

### ISSUE THREAD

**Issue by smcoll** [Ashald/EnvFile#24]
This happened after i updated the plugin to 2.0.  i have a `.env` file enabled and selected in the "EnvFile" tab, per instructions.  When i run the configuration, no env vars have been applied.  For the moment, i'm manually adding env vars the old way, to get by.  Let me know if there's any further information which would be helpful.

PyCharm 2016.3.2 build 163.10154.50

**Comment by ashald** [comment]
Can you please upload a screenshot of the `EnvFile` tab? Also, is there anything in `Event Log` (it's either in bottom right corner if you have toolbar displayed or you can open it via bottom-left corner popup)?

**Comment by smcoll** [comment]
Nothing in the event log except "Tests Failed", but your request for a screenshot smoked out the issue.  i had pointed it to the wrong file; a file called `.env.local` which is formatted like a bash file.  Thanks!
