### ISSUE TITLE
Environment variables aren't loaded in IDEA

### ISSUE THREAD

**Issue by yoanthiebault** [Ashald/EnvFile#27]
Hi,

First of all, thank you for this nice plugin ! 

I installed it but it didn't load the environment variables with IntelliJ IDEA Community Edition 2016.3.5. For information:
- Here is the run configuration:  ![settings](https://cloud.githubusercontent.com/assets/10627530/23711628/acfc6778-0420-11e7-96a3-9b5fcd83c3fd.PNG)
- The .env file just contains `FOO=BAR`
- `System.getenv().containsKey("FOO")` returns `false`

Could you please tell me if I missed something ?

Yoan

**Comment by ajaxon** [comment]
I just tried using the plugin with IntelliJ IDEA 2016.2.5 and mine are not loading either.

**Comment by ashald** [comment]
Looks like a bug. @yoanthiebault opened a PR #28 which looks good so once it's merged I'll release a new version.
