### ISSUE TITLE
Can't manually enter file paths

### ISSUE THREAD

**Issue by birkholz** [Ashald/EnvFile#29]
In 1.0.1, you could manually type in the path to the env file, but in 2.0.0 it requires a file dialog. However, in OSX's default file dialog, there's no way to select hidden files, and all dot-prefixed files are hidden, including `.env`. 

This means I had to downgrade to 1.0.1 in order to select my `.env` files.

**Comment by ashald** [comment]
@birkholz thanks for the issue report! Do you have an idea what could be the best UI for manual entry?

**Comment by ashald** [comment]
I'm sure it's not the best way around but as a quick solution - I added some code that allows manual editing for paths in EnvFile table on double click.

**Comment by ashald** [comment]
Version `2.1.0` was release and pending review form JetBrains.

**Comment by birkholz** [comment]
@Ashald Awesome, that works for me, thanks for the quick fix. :+1:
