### ISSUE TITLE
Support EnvFile in Python Console and for manage.py

### ISSUE THREAD

**Issue by dmwyatt** [Ashald/EnvFile#34]
There are two other places besides run configurations where you might need your .env file read.

Settings > Languages & Frameworks > Django > Manage.py tasks > Environment variables
Settings > Build, Execution, Deployment > Console > Django Console > Environment variables

If .env file isn't supported here, I have to manually copy all required values from .env to each of these places.

**Comment by ashald** [comment]
Unfortunately this is not feasible to implement with the current state of the JetBrains extensions API. Please see https://github.com/Ashald/EnvFile/issues/7 for details.
