### ISSUE TITLE
EnvFile seems to be broken for PyCharm 2017.1.2 

### ISSUE THREAD

**Issue by jpoutrin** [Ashald/EnvFile#35]
Following the steps, 
using a bash or .env file, does not pick up the variables....

**Comment by refack** [comment]
I just check. It works for me. (on Windows).
@jpoutrin try YAML file, they work best for me.

**Comment by ashald** [comment]
@jpoutrin can you please share mode details? Did it work for you with previous versions? Can you share your `.env` file? Bash files are not supported, just for the record.

**Comment by jpoutrin** [comment]
@Ashald 
sorry I just installed the plugin.
I also want to stick to bash format as i am using direnv alongside.
not sure where to get some log for you guys.
[envrc.txt](https://github.com/Ashald/EnvFile/files/968001/envrc.txt)

**Comment by ashald** [comment]
@jpoutrin this plugin doesn't support bash and there is no feasible way to implement it so far. Please take a look at a proposed workaround https://github.com/Ashald/EnvFile#bash-workaround
