### ISSUE TITLE
go support

### ISSUE THREAD

**Issue by nabeelio** [Ashald/EnvFile#37]
It'd be nice to get some support for golang, seems to be used somewhat pervasively. Thanks!

**Comment by ashald** [comment]
I will see whether it can be done, please hold on...

**Comment by ppwfx** [comment]
yeah would be really cool if you could add support for goglang! :) I tried to implement it myself, but Im getting nowhere.. :/

**Comment by ppwfx** [comment]
push

**Comment by ashald** [comment]
I'll try to take a look at it as fast as I'll get a bit of free time. ;)

**Comment by ashald** [comment]
I spent some time poking around Gogland sources and unfortunately it seems that it's not possible to integrate with it at this time. The key point for an IDE or run configuration to be compatible with this plugins is to integrate with so-called `runConfigurationExtension` interfaces one way or another. There is a generic one used by IDEA and there are specific ones used by PyCharm/RubyMine. Unfortunately Gogland doesn't work with any run configuration extensions. :( Let's hope they will fix that by the time of final release or if no I'll try to look for alternative integration options (that most probably will include soma monkey-patching and will make plugin more fragile).

**Comment by nabeelio** [comment]
@Ashald that's fair. FYI, they do have the Gogland plugin in Intellij proper, I guess that's more the one I was referring to.

**Comment by ashald** [comment]
I'm not 100% sure but I think the IDEA plugin is the same code that is used in Gogland.

**Comment by nabeelio** [comment]
Ah I see what you mean, so that interface differs in the plugin. Maybe open a ticket on their tracker, they're pretty good about that stuff

**Comment by davidpope** [comment]
I'd love to use this plugin! But it looks like they didn't add the support you need in the final release. :( I created https://youtrack.jetbrains.com/issue/GO-5323 to ask for the right support, I hope I got the wording right.

**Comment by amccarri** [comment]
Looks like the support you need has been added to Goland/Intellij 2018.1.  Any movement on this since the 2018.1 releases?

**Comment by j0hnsmith** [comment]
Bump, looking forward to using this in Goland!

**Comment by sefasenturk95** [comment]
Another bump, I would love this..

**Comment by ppwfx** [comment]
https://github.com/joho/godotenv for the meantime..

**Comment by ashald** [comment]
This is not released yet but already merged into `develop` (big thanks to @Kelnor277). Release coming within a week, closing the issue to clear list of feature requests.
