### ISSUE TITLE
support env files for Gradle Run/Debug configurations (IDEA 2017.2)

### ISSUE THREAD

**Issue by jack-kerouac** [Ashald/EnvFile#38]
With IntelliJ IDEA 2017.2, environment variables are supported for Gradle Run/Debug configurations: https://www.jetbrains.com/idea/whatsnew/#v2017-2-gradle.

It would be great if the "EnvFile" tab would also be available for Gradle configurations.

**Comment by ashald** [comment]
Cannot say for sure yet but it seems that it might be possible - take some time to figure out available integration points...

**Comment by LutzStrobel** [comment]
I use Idea 2017.3.3 and env version 2.1.0.
The env-file tab is available but does not have any effect.
The variables used are asfollows:
EXT_DATABASE_PASSWORD=cde
EXT_DATABASE_PORT=5432
EXT_DATABASE_SCHEMA=cde
EXT_DATABASE_USER=cde
...

Whats up with my doing?

**Comment by ashald** [comment]
I just tried it with `2017.3.4` and it worked fine. Did you verify that both the plugin and the file are enabled?
![enabled](https://user-images.githubusercontent.com/397987/37071459-9df0c8f4-218a-11e8-9a85-170cefd1aeb3.png)

Also, I wonder if it might be related to the content of your file and parser used. My test file looked exactly this way:
```
EXT_DATABASE_PASSWORD=cde
EXT_DATABASE_PORT=5432
EXT_DATABASE_SCHEMA=cde
EXT_DATABASE_USER=cde
```

**Comment by ashald** [comment]
Ah, wait, I used an `Application` run configuration.

Can you please provide me with a minimal `Gradle` project I can use to run some simple app that prints its environment?

**Comment by LutzStrobel** [comment]
I will try it to morrow in the morning.

**Comment by mertvetsky** [comment]
I met same problem: running by gradle tasks do not uses file for env import on IDEA community 2018.2

How check it:
1. Create new gradle project with java
2. Edit `build.gradle` like this (just add application plugin and mainClassName):
```.gradle
plugins {
    id 'java'
    id 'application'
}

group 'mert'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

mainClassName="App"
```
3. Create file ./src/main/java/App.java:
```.java
public class App {
    public static void main(String[] args) {
        System.out.print(System.getenv().getOrDefault("FOO", "EMPTY"));
    }
}
```
4. Run application/run task from gradle sidebar
5. Then edit created Run/Debug config for import file with parameter `FOO=BAR`

PS
When this project runs by "play button" opposite main method it works fine.

**Comment by yelhouti** [comment]
Same issue here, any ETA on this please?

**Comment by ashald** [comment]
@yelhouti contributions are welcome!

**Comment by ashald** [comment]
Actually, I was able to figure out a hack to make it work. See https://github.com/ashald/EnvFile#experimental-integrations for details.

I just released `v3.2.0` and it may take up to 2 days for JetBrains to process the release, in meantime you can download release directly and install it manually from https://github.com/ashald/EnvFile/releases/tag/v3.2.0

Kudos to @mertvetsky for reproduction steps!

![May242019123614](https://user-images.githubusercontent.com/397987/58343972-7ba66100-7e22-11e9-915e-6f7efe65602b.gif)

**Comment by yelhouti** [comment]
great thank you very much :)

**Comment by mcdan** [comment]
I think this may be broken in:
```
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 23, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.28-041928-generic
```
I followed the steps from @mertvetsky and still get the following even after enabling the `Experimental Integrations`:
```
4:28:53 PM: Executing task 'App.main()'...

> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

> Task :App.main()
EMPTY
```
