### ISSUE TITLE
add support for toml

### ISSUE THREAD

**Issue by stableShip** [Ashald/EnvFile#4]
add support for toml??

**Comment by Ashald** [comment]
What's your usecase? As I see there are 'sections' with values and values outside of sections. So we either need to read values in the root or take them from one of sections...

**Comment by ashald** [comment]
As the use-case is not entirely clear to me and nobody is willing to assist with clarifications I have no other choices except close the issue. If somebody needs this features - please feel free to comment here or open a new issue.
