### ISSUE TITLE
couldn't set ".env" file that isn't have a name.

### ISSUE THREAD

**Issue by zironycho** [Ashald/EnvFile#42]
couldn't set ".env" file that isn't have a name.

**Comment by ashald** [comment]
Sorry, can you describe the issue in a little bit more details?

**Comment by zironycho** [comment]
I am using pycharm in macOS. Adding env-file not started with dot is worked. However I have env-file started with dot, and it couldn't see in adding dialog window.

**Comment by ashald** [comment]
Ah, that's a know "feature" of macOS - just press `Cmd` + `Shift` + `.` (dot) to toggle hidden files view - works both in "Open dialog" and in Finder.

**Comment by zironycho** [comment]
Ohhhh,  sorry for my mistake.
Thank you.

**Comment by ashald** [comment]
That's not your mistake - that's usability issue on macOS. Though, I will see if I can add a note into the UI about that hotkey. 😀
