### ISSUE TITLE
cannot set PYTHONPATH?

### ISSUE THREAD

**Issue by melchoir55** [Ashald/EnvFile#45]
This plugin seems to work well setting our environment variables.

There is one var in particular, however, which doesn't seem to be set when we put it in the env file. That is PYTHONPATH.

My test was to place PYTHONPATH in the run config env vars and print out the var to console. This worked.

When I placed PYTHONPATH in the .env file and printed the var out to console, this did not work. However, other vars did.

**Comment by ashald** [comment]
Hm, interesting, I will try that out.

**Comment by jirkadanek** [comment]
Extending PYTHONPATH works for me in run configurations; intellij (with Python plugin) does not pick it up in editor for code completion, but I did not expect it to. One problem was that my .env file got somehow detected wrong, or something. I did not investigate why. I had to copy `.env` into `my.env` and add it again to run configuration, then it all worked

![image](https://user-images.githubusercontent.com/17877663/62193746-b378da00-b378-11e9-914c-29fd10b3c2c2.png)

**Comment by ashald** [comment]
I was wondering why this issues sounds familiar to me but couldn't figure it out until you brought up `PYTHONPATH`.
`PyCharm` handles it in a special way and my personal rule of thumb is to avoid touching it as much as I can.

To the best of my knowledge it won't work with many (or any?) other envfile implementations, but you can leverage the `EnFIle` variable substitution as discussed in https://github.com/ashald/EnvFile/issues/88.
