### ISSUE TITLE
Dereferencing variables in Run Config fields..

### ISSUE THREAD

**Issue by raffian** [Ashald/EnvFile#48]
Created `environment.env` file, configured on EnvFile tab, now I'm trying to use variables in Run Config, I was banking on using variables like this because I have many run configs that share the same arguments, but the variable is not replaced; is this supported?

```#environment.env
CONNECT_URL=tcp://myhost.com
```
![env-plugin](https://user-images.githubusercontent.com/4412120/32741463-51dac538-c874-11e7-938e-b2a4121e8d9b.png)

**Comment by ashald** [comment]
I hate to bring in bad news but this is out of control of the plugin. The only thing that this plugin does - it modifies a map of available environment variables available for RunConfiguration. How to process program values and other fields - that's up to the IDEA on its own.
I personally agree with you that it would be amazing to have such a feature so I'd suggest you filing an issue in JetBrains YouTrack. I'd happily upvote it!
