### ISSUE TITLE
Support for default values in .env

### ISSUE THREAD

**Issue by ilansh** [Ashald/EnvFile#49]
Would it be possible to support syntax of default values in .env files?
As in 
```
DB_HOST=${DB_HOST:-127.0.0.1:3306}
```

This can prove very helpful for my usage pattern.

**Comment by ashald** [comment]
This will not be compatible with the underlying .env file spec, to the best of my knowledge, but I'm considering adding an option to allow variables expansion. Please follow #16 for updates.
