### ISSUE TITLE
Use variables in env file

### ISSUE THREAD

**Issue by jommgoncalves** [Ashald/EnvFile#50]
Hi,

It is possible has default variables in env file?

For instance:
HOST="x"
URL_A="${HOST}/cats"
URL_B="${HOST}/dogs"

Best regards

**Comment by ashald** [comment]
I think there were numerous requests for this. This will not be compatible with the underlying `.env` file spec, to the best of my knowledge, but I'm considering adding an option to allow variables expansion. Stay tuned.

**Comment by ashald** [comment]
Actually, there is already an issue for this - #16. I'm going this one as a duplicate in favor of that one. Follow referenced issue instead please.
