### ISSUE TITLE
[Bug] Backslash is removed from env values

### ISSUE THREAD

**Issue by Greyvend** [Ashald/EnvFile#52]
Given the following line in the *.env file:

`TEST_VAR=value\1`

the resulting environment variable set in the system is this:

`TEST_VAR=value1`

OS: Windows 10
Plugin version: 2.1.0

**Comment by ashald** [comment]
Hm, did you try wrapping value in double quotes? It's definitely a shame the value is mangled - I'll look into a fix for this. Thanks for reporting!

**Comment by ashald** [comment]
Turns out it was the same issue as #32

**Comment by ashald** [comment]
Added a test, will be included into next release.
