### ISSUE TITLE
project scope and module scope support

### ISSUE THREAD

**Issue by cn-src** [Ashald/EnvFile#55]
In every one "Run/Debug" need to enable EnvFile, This can be very tedious.
So it's even better if the plugin have a wider scope of support.

**Comment by ashald** [comment]
Did you try editing defaults to enable the plugin for all new run configs? ![defaults](https://user-images.githubusercontent.com/397987/37070611-413dc548-2186-11e8-96ff-31282727e141.png)

**Comment by cn-src** [comment]
Thank you very much for suggesting that this is exactly what I need.

**Comment by ashald** [comment]
You're welcome! We should just thank JetBrains for an amazing product they created! 😄
