### ISSUE TITLE
`export key=value` support

### ISSUE THREAD

**Issue by jpsenior** [Ashald/EnvFile#56]
Hi there!

I've got a project that dynamically creates env files in the format

```
export FOO=bar
export ABC=onetwothree
```

To use this plugin, I Currently just open the file  and replace 'export ' with '' - this is a little bit of a slowdown because the env file ends up changing, and I have to maintain a copy somehow outside of source control.

Is it possible for this project to selectively recognize if a line says 'export XX' and just drop 'export ' for importing variables?  In all I imagine it'd be the right thing to do :)

**Comment by ashald** [comment]
Does this workaround work for you https://github.com/Ashald/EnvFile#bash-workaround ?

**Comment by ashald** [comment]
Due to the lack of activity on this issue I will consider it to be resolved given that a workaround was proposed. Please feel free to reopen or submit another issue in case workaround does not sound like a good solution to you.
