### ISSUE TITLE
EnvFile tab not appearing

### ISSUE THREAD

**Issue by brock** [Ashald/EnvFile#59]
Any suggestions on what to do if I'm not seeing the EnvFile tab in a new debug configuration after a reboot?

EDIT: to clarify I'm not seeing this in the Docker configurations, but I am seeing them in others

**Comment by ashald** [comment]
This means that Docker configurations do not use standard interfaces for run configurations. It might or might not be possible to implement this integration. I would need to know more details like what IDE you use, what version and what plugin you installed to get Docker run configuration (if any).

**Comment by brock** [comment]
Thanks @Ashald 

I'm using PyCharm 2018.1.1 on OSX, and I'm using (as far as I know) the built-in IntelliJ Docker plugins for Debug Configurations. I'm not seeing the Env File tab for Docker image, Docker-Compose, and Dockerfile.

Feel free to close if this is out of your control, or leave open so others know that it isn't supported from their end.

**Comment by ashald** [comment]
It _might_ be possible to add support for this - I'll have to check how exactly those run configurations work. Due to limited time, I most likely will get to it closer to the end of the month.

**Comment by brock** [comment]
Sure sure, just wanted to file a report and see if I was missing something obvious. Many thanks

**Comment by orichardson** [comment]
I also can't find an EnvFile tab --- IDEA 2018.1.1, Windows 10

**Comment by ashald** [comment]
@orichardson what kind of run configuration you're using?

**Comment by edsion1107** [comment]
I also can't find an EnvFile tab --- PyCharm 2018.1.3, Windows 7, running python script.

**Comment by ashald** [comment]
@edsion1107 can you please provide 2 screenshots showing plugin version from IDE settings and Run Configuration window like in examples below:
![screen shot 2018-05-21 at 21 00 17](https://user-images.githubusercontent.com/397987/40336879-246af068-5d3a-11e8-8e8e-f5ae3c58d7fb.png)
![screen shot 2018-05-21 at 21 00 34](https://user-images.githubusercontent.com/397987/40336880-247ccba8-5d3a-11e8-93ae-bbe6355cb61e.png)

**Comment by edsion1107** [comment]
![tim 20180522140739](https://user-images.githubusercontent.com/1925286/40344929-9db073a0-5dc9-11e8-97f0-7ce8420dfb70.png)
![image](https://user-images.githubusercontent.com/1925286/40344933-9f278a48-5dc9-11e8-9373-d11b95ec8af8.png)


Sorry I know where the problem is, I installed the wrong plugin.

**Comment by explaura** [comment]
Also experiencing this issue with IntelliJ 2018.1.4 on OSX.

**Comment by ashald** [comment]
@lbran can you do the screenshots as I did above in https://github.com/Ashald/EnvFile/issues/59#issuecomment-390830066 ?

**Comment by explaura** [comment]
@Ashald 
![screen shot 2018-05-23 at 1 24 49 pm](https://user-images.githubusercontent.com/19300547/40402159-79448d5c-5e8d-11e8-9771-7088ad7a9bb9.png)
![screen shot 2018-05-23 at 1 29 36 pm](https://user-images.githubusercontent.com/19300547/40402163-7c1d7020-5e8d-11e8-9be5-de4520721631.png)

**Comment by ashald** [comment]
@lbran It looks like you're trying to use it with NodeJS run configuration which is not currently supported (see list of supported run configurations in readme https://github.com/Ashald/EnvFile#supported-platforms) - I'd suggest you upvoting https://github.com/Ashald/EnvFile/issues/54 so I'll take a look into it when I will have a chance to.

**Comment by mlsquires** [comment]
I just installed this on GoLand and RubyMine. I've got version 0.7. I'm on MacOs. The EnvFile tab doesn't show up in either of those two IDEs.
