### ISSUE TITLE
NullPointerException related to filename of .env

### ISSUE THREAD

**Issue by smcoll** [Ashald/EnvFile#6]
When using this plugin, i got a `java.lang.NullPointerException`, and after some fiddling around, it seemed to be related to the filename of the .env i was using: ".env.local".  When i changed it to "dev.env", it worked fine.

**Comment by Ashald** [comment]
Oh, that's a nice catch! Thanks! I will release new version soon with fix for this.

**Comment by Ashald** [comment]
Unfortunately I wasn't able to reproduce the issue. @smcoll can you please provide more details if you still able to reproduce it?

**Comment by smcoll** [comment]
@Ashald no longer seems to be a problem, using 2016.1.4.  Maybe it was a PyCharm bug that has since been fixed.

**Comment by ashald** [comment]
@smcoll thanks for the update.
