### ISSUE TITLE
Default env file should be ~/.envrc

### ISSUE THREAD

**Issue by ssbarnea** [Ashald/EnvFile#60]
I would recommend going to a default ``.envrc`` file, as this became some kind of defacto standard for environment files, with more and more tools supporting it. 

For example direnv uses it and it can even load the best file to use based on current folder. The tool would look for the file in current folder and its parents until it reaches user home directory. This allows users to share env files across multiple projects.

**Comment by ashald** [comment]
I'm actually not familiar with `.envrc` - will have to look into it. On the other hand, what would you say about a workaround proposed here https://github.com/Ashald/EnvFile/issues/55#issuecomment-371002257 ?

**Comment by ashald** [comment]
Due to the lack of activity on this issue I will consider it to be resolved given that a workaround was proposed. Please feel free to reopen or submit another issue in case workaround does not sound like a good solution to you.

**Comment by gleber-da** [comment]
@Ashald The `.envrc` file is an shell script which is sourced automatically by multiple local env-management tools, especially http://direnv.net/. This could work the following way:
1) If `.envrc` file is present
2) If `direnv` executable is on `$PATH`
3) Do equivalent of `(cd $PROJECT && direnv export json)` and record the variables encoded in the returned JSON
4) Filter out env variables which start with `DIRENV_`
5) Set all the remaining environmental variables for the currently opened project

**Comment by gleber-da** [comment]
A good inspiration would be `emacs-direnv` package:
https://github.com/wbolster/emacs-direnv
