### ISSUE TITLE
Path and type disappear upon checking the select checkbox

### ISSUE THREAD

**Issue by raveendrahegde** [Ashald/EnvFile#61]
Once the checkbox is selected the path and type info disappear and the come back when unchecked. However the env file are being read correctly. 

OS: macOS 10.13.4
![screen shot 2018-05-11 at 1 10 59 pm](https://user-images.githubusercontent.com/5344361/39946231-45906784-5522-11e8-82a9-9e7becc3e248.png)
![screen shot 2018-05-11 at 1 11 08 pm](https://user-images.githubusercontent.com/5344361/39946232-45a5432a-5522-11e8-81cf-6c236b5c848e.png)

**Comment by ashald** [comment]
I think the issue here is that whenever file is selected its path is displayed in white which doesn't work well with light themes. That sounds like a bug and should be fixed - thanks for the discovery!

**Comment by ashald** [comment]
Fixed, will be included in next release.
