### ISSUE TITLE
new release to support Goland?

### ISSUE THREAD

**Issue by mlsquires** [Ashald/EnvFile#69]
Just saw that you've added Goland support. Any chance of a release?

**Comment by ashald** [comment]
New release is coming soon. Meantime, you can use build instructions from readme and install plugin from a file if you need it ASAP.

**Comment by ashald** [comment]
I just uploaded `v3.0.0` to JetBrains plugin registry. It may take up to 2 business day for update to be processed. Meantime you can download plugin archive from the release page [v3.0.0](https://github.com/Ashald/EnvFile/releases/tag/v3.0.0) and install it from disk.

**Comment by zolotov** [comment]
@Ashald 3.0.0 still excludes GoLand as a supported product. Is this intentional?

![image](https://user-images.githubusercontent.com/140920/47855459-ba78b900-ddf5-11e8-9b7d-a74743d54375.png)

**Comment by ashald** [comment]
Huh, that looks like a bug for me. I test the plugin by installing it manually from disk but not from the registry. I'll look into it - thanks. Meantime, you can download `zip` file from releases tab and install it manually.

**Comment by zolotov** [comment]
@Ashald any news? I can ask plugin's repository admins to mark the plugin as compatible with GoLand if you have no time for this right now. Is this ok for you?

**Comment by ashald** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/397987/48668244-b5cf2880-eab6-11e8-875e-6de4ffc0373b.png">
Should be fixed now.

**Comment by zolotov** [comment]
> GoLand build 131.0+

This leads to ClassNotFoundExceptions and other problems on the runtime. Extensions your plugin uses were added in 181.4203+ builds.

**Comment by ashald** [comment]
Good to know - thanks.
