### ISSUE TITLE
Plugin not working in Intellij 2018.3.5

### ISSUE THREAD

**Issue by rafiron** [Ashald/EnvFile#78]
The plugin doesn't seem to be working with my Intellij.  Here are the details of my setup:

IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

Other people also appear to be facing a similar issue : [https://plugins.jetbrains.com/plugin/7861-envfile#comment=31310](https://plugins.jetbrains.com/plugin/7861-envfile#comment=31310)

**Comment by rafiron** [comment]
It appears to be working with `JAR application` run configuration but not with `Spring Boot` configuration

**Comment by ashald** [comment]
Did it work before - with previous versions? Or you haven't tried?

**Comment by rafiron** [comment]
I used to use it with `Spring Boot` run configuration and it used to run perfectly. Now it doesn't work. The options to add/remove/edit the .env files are not visible and my existing run configurations which used to run just fine no longer run now.

**Comment by ashald** [comment]
I will take a look whenever I have a chance but it is likely to be related to API incompatibility. If it's just plugin interface change then it should be easy to fix it. If they removed the plugin interface altogether it may no longer be possible to provide the integration.

**Comment by ffejer** [comment]
I loads the env files no problem but can't reference them run configuration when passing arguments.
So by not working you mean the same thing?

My setup
IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
Subscription is active until March 29, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by rafiron** [comment]
For me it's not even loading the env files nor providing me the option to add or remove files. But it's only happening for `Spring Boot` run configuration. It works fine with other run configuration. (Tried with the `JAR application` run configuration and it works)

**Comment by rafiron** [comment]
Here is a snapshot of `EnvFile` plugin configuration section under `Spring Boot` Run/Debug Configurations.
The options for edit, add or remove aren't available. For the configurations that were used previously are listed under the list of envs but they don't seem to work.

<img width="733" alt="Screenshot 2019-04-02 at 3 57 11 PM" src="https://user-images.githubusercontent.com/24583737/55395917-45eea580-5560-11e9-8c2a-74892bd89bcd.png">

Here is a sample snaphot for the `JAR Application` Run/Debug configuration (provides the options and also works)

<img width="731" alt="Screenshot 2019-04-02 at 4 00 43 PM" src="https://user-images.githubusercontent.com/24583737/55396086-b269a480-5560-11e9-8f33-9a5fb6233c4a.png">

**Comment by jpayne97** [comment]
You might not be able to tell from your theme, but there is an invisible scroll bar on the right side of the window just past the vertical line to the right of "Type" header.

**Comment by rafiron** [comment]
Cleared the `.idea` directory and on-reopening the project the plugin seems to be now working. Also thanks @jpayne97 for the scrolling information.

**Comment by ashald** [comment]
So... not an issue anymore?

FWIW, the screenshots that I see above do not have a checkmark next to "Enable EenvFile" so it's expected that all controls are disabled.

**Comment by ffejer** [comment]
I am not sure, my use-case is the following:

I am setting a variable in a .env file like so:
`VERSION=1.0`

Creating a java application run conf with envfile enabled, loading the .env file and in the run configurations in the program arguments field I am trying to reference that variable like `${VERSION}`, it doesn't get substituted. I can see it if I query the system properties (`System.getenv()`). Normal environmental variables work (e.g. `${PATH}` )

Am I doing something wrong? Or is this not a valid use-case?

**Comment by ashald** [comment]
@ffejer could you post a screenshot of your run configuration? Does it work with environment variables that you specify via native IDEA interface?

I'm afraid variable substitution in command line might be beyond something this plugin could do. Usually it's handled by the shell but I don't think IDEA runs a sub-shell to execute the program and therefore I wouldn't expect it to work unless they explicitly implemented that feature.

**Comment by ffejer** [comment]
Sure thing.

![image](https://user-images.githubusercontent.com/1386880/56642553-f93a4e00-6677-11e9-8aae-29c0c726ccfd.png)

![image](https://user-images.githubusercontent.com/1386880/56642592-13742c00-6678-11e9-9da8-1ba071f7bfdb.png)

contents of my.env:
`MY_ENV_VAR=foobar`

When running this config `${MY_ENV_VAR}` is not substituted and `${alias}` native one set in intellij is.

**Comment by rafiron** [comment]
> So... not an issue anymore?
> 
> FWIW, the screenshots that I see above do not have a checkmark next to "Enable EenvFile" so it's expected that all controls are disabled.

Although I pasted the screenshots of it being disabled, I tested them with enable before posting the issue. The issue got resolved once I removed the `.idea` directory and like @jpayne97 pointed out, due to the theme the scroll bar wasn't visible but was present there.

**Comment by ashald** [comment]
@ffejer forgive me if I'm missing something but the 1st of the screenshots you posted doesn't show any values in `Environment Variables`. Did you just omit setting it while doing this screenshots or you set it some other way?

**Comment by ashald** [comment]
@rafiron as much as I can say, it seem that plugin does work with `2018.3.5`. It appears that there might've been some issues during upgrade of the IDE to that version that potentially resulted into corruption of project files. This is not nice but probably something we can live with. I'd be inclined to close this issue and @ffejer's case probably deserves its own issue.

**Comment by ffejer** [comment]
@ashald I haven't set any environment variables in the runconf but globally inside IntelliJ. Those work. I still don't get if what I am tryna do is what the plugin is meant for. ;-)
