### ISSUE TITLE
fields overlap when there are multiple projects in the current context

### ISSUE THREAD

**Issue by syphar** [Ashald/EnvFile#8]
The first field here is the project to select, it overlaps with the env-file field. 
![screenshot 2015-12-04 09 14 52](https://cloud.githubusercontent.com/assets/540890/11584837/9a395d4a-9a67-11e5-90cd-1a1b1067c60a.png)

clicking on them does bring me to the project-field.

**Comment by davidfraser** [comment]
This makes using this quite hard work, which is a shame as it's a great extension

**Comment by Ashald** [comment]
Oh, looks awful. :)

What version of PyCharm you're using?

I'll try to fix that till the end of the month (sorry, super-busy with other things so hard to find spare time)

**Comment by davidfraser** [comment]
I've had this on PyCharm 2016.1 (and the patch releases). Thanks!

**Comment by Ashald** [comment]
WIP, trying to figure out how to hack into PyCharm UI properly. :)

**Comment by Ashald** [comment]
Fixed, expect a new version soon.
