### ISSUE TITLE
Cannot select .env files on macOS

### ISSUE THREAD

**Issue by jimklo** [Ashald/EnvFile#93]
Seems like this could be a great plugin, however since it doesn't automatically pickup the `.env` files in the project root, it seems I have to manually select.

On macOS (within PyCharm - but maybe other IDEA based projects as well), I'm unable to navigate to select the `.env` file as since it's a 'dot file', it is hidden from the file selector.

The plugin needs to allow one of three options:
1. select the `.env` file by default located in the project root
2. have the _add .env file_ menu open a navigator that shows hidden dot files.
3. give me the ability to just specify an absolute path via cut/paste or typing.

**Comment by ashald** [comment]
Thanks for the feedback!

Apparently you're facing an issue with hidden files in `macOS` - this use case is actually covered in the [readme](https://github.com/ashald/EnvFile#hidden-files).

With regards to other suggestions:
1) I prefer explicit behaviors over implicit and do not believe plugin can make an assumption about the default file to load for _all_ its users. You may be able achieve desired behavior for yourself by editing run configuration templates in your IDE.
2) This is covered in the [readme](https://github.com/ashald/EnvFile#hidden-files).
3) This is already supported, please see https://github.com/ashald/EnvFile/issues/62#issuecomment-390831747 for details.
