### ISSUE TITLE
Support for WebStorm?

### ISSUE THREAD

**Issue by tonioriol** [Ashald/EnvFile#94]
Would it be possible to enable support for WebStorm?

**Comment by ashald** [comment]
What kind of run configurations are you using in WebStorm?

**Comment by tonioriol** [comment]
i have a node project with jest for testing and the test environment variables are loaded from an env file.

**Comment by tonioriol** [comment]
That is done in a js file that is called to run all tests from the console. That file loads the env variables from a file and then runs jest programmatically. What i'd like is to run jest straight out from the run config, and load the env from the file.

**Comment by ashald** [comment]
`NodeJS` support in `WebStorm` if handled by the special JetBrains plugin - it's just bundled by default with `WebStorm` but you also can install it in other their IDEs. What this means, is that for this to work we need to integrate with `NodeJS` plugin and it actually lacks extension points required by `EnvFile`.
Please follow #36 for updates.
Other community members raised this with JetBrains and you can help by upvoting the ticket: https://github.com/ashald/EnvFile/issues/36#issuecomment-496575370
