### ISSUE TITLE
ENV not work PyCharm

### ISSUE THREAD

**Issue by gshmu** [Ashald/EnvFile#97]
`VERSION 1.0` not work.

but `VERSION=1.0` worked.

**Comment by ashald** [comment]
Could you provide more details please?

**Comment by gshmu** [comment]
PyCharm 2019.2.3 (Professional Edition)
Build #PY-192.6817.19, built on September 25, 2019

Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16

create env file, and enable it, using `VERSION 1.0` not work.  worked after add `=`.

**Comment by ashald** [comment]
The `.env` file format requires `=` between name and value - please see examples in docs https://github.com/ashald/EnvFile#env

**Comment by gshmu** [comment]
![image](https://user-images.githubusercontent.com/1797676/68830840-ca54f980-06e7-11ea-90f6-ef211065f232.png)
the doc contain both '=' and 'space'
